"""Bazel rules for CommonAPI code generation from FIDL files."""

# List of all files generated by CommonAPI generators
_GENERATED_FILES = [
    # Core generator outputs (headers only)
    "v1/com/kpit/acc/services/accInputServiceInterface.hpp",
    "v1/com/kpit/acc/services/accInputServiceInterfaceProxy.hpp",
    "v1/com/kpit/acc/services/accInputServiceInterfaceProxyBase.hpp",
    "v1/com/kpit/acc/services/accInputServiceInterfaceStub.hpp",
    "v1/com/kpit/acc/services/accInputServiceInterfaceStubDefault.hpp",
    "v1/com/kpit/acc/services/accOutputServiceInterface.hpp",
    "v1/com/kpit/acc/services/accOutputServiceInterfaceProxy.hpp",
    "v1/com/kpit/acc/services/accOutputServiceInterfaceProxyBase.hpp",
    "v1/com/kpit/acc/services/accOutputServiceInterfaceStub.hpp",
    "v1/com/kpit/acc/services/accOutputServiceInterfaceStubDefault.hpp",
    # SomeIP generator outputs (headers and implementation)
    "v1/com/kpit/acc/services/accInputServiceInterfaceSomeIPProxy.hpp",
    "v1/com/kpit/acc/services/accInputServiceInterfaceSomeIPProxy.cpp",
    "v1/com/kpit/acc/services/accInputServiceInterfaceSomeIPStubAdapter.hpp",
    "v1/com/kpit/acc/services/accInputServiceInterfaceSomeIPStubAdapter.cpp",
    "v1/com/kpit/acc/services/accInputServiceInterfaceSomeIPDeployment.hpp",
    "v1/com/kpit/acc/services/accInputServiceInterfaceSomeIPDeployment.cpp",
    "v1/com/kpit/acc/services/accOutputServiceInterfaceSomeIPProxy.hpp",
    "v1/com/kpit/acc/services/accOutputServiceInterfaceSomeIPProxy.cpp",
    "v1/com/kpit/acc/services/accOutputServiceInterfaceSomeIPStubAdapter.hpp",
    "v1/com/kpit/acc/services/accOutputServiceInterfaceSomeIPStubAdapter.cpp",
    "v1/com/kpit/acc/services/accOutputServiceInterfaceSomeIPDeployment.hpp",
    "v1/com/kpit/acc/services/accOutputServiceInterfaceSomeIPDeployment.cpp",
]

def _commonapi_library_impl(ctx):
    """Implementation of commonapi_library rule."""
    
    # Declare individual output files
    output_files = []
    for file_path in _GENERATED_FILES:
        output_file = ctx.actions.declare_file(ctx.label.name + "/" + file_path)
        output_files.append(output_file)
    
    # Get input files
    fidl_file = ctx.file.fidl
    fdepl_file = ctx.file.fdepl
    
    # Get generator tool files and find the executables
    core_gen_files = ctx.attr.core_generator.files.to_list()
    someip_gen_files = ctx.attr.someip_generator.files.to_list()
    
    # Find the generator directory by looking for files under generators/core/ or generators/someip/
    # Skip bin/ directory as it only contains symlinks
    core_gen_dir = None
    for f in core_gen_files:
        if "generators/core" in f.path and f.basename == "commonapi-core-generator-linux-x86_64":
            core_gen_dir = f.dirname
            break
    
    someip_gen_dir = None
    for f in someip_gen_files:
        if "generators/someip" in f.path and f.basename == "commonapi-someip-generator-linux-x86_64":
            someip_gen_dir = f.dirname
            break
    
    if not core_gen_dir or not someip_gen_dir:
        fail("Could not find generator executables in generators/ directories")
    
    # Determine output directory (parent of first output file)
    output_dir = output_files[0].dirname + "/.."
    
    # Create script to run generators
    script = ctx.actions.declare_file(ctx.label.name + "_codegen.sh")
    
    script_content = """#!/bin/bash
set -e

# Create output directory
mkdir -p {output_dir}

# Create temporary work directory
WORK_DIR=$(mktemp -d)
trap "rm -rf $WORK_DIR" EXIT

# Copy core generator to writable location
mkdir -p $WORK_DIR/core_gen
cp -r {core_gen_dir}/* $WORK_DIR/core_gen/

# Copy someip generator to writable location  
mkdir -p $WORK_DIR/someip_gen
cp -r {someip_gen_dir}/* $WORK_DIR/someip_gen/

# Create Eclipse workspace directories
mkdir -p $WORK_DIR/core_workspace $WORK_DIR/core_config
mkdir -p $WORK_DIR/someip_workspace $WORK_DIR/someip_config

# Run core generator
cd $WORK_DIR/core_gen
./commonapi-core-generator-linux-x86_64 \\
    -data $WORK_DIR/core_workspace \\
    -configuration $WORK_DIR/core_config \\
    -sk -dest {output_dir} {fidl_path}

# Run SomeIP generator
cd $WORK_DIR/someip_gen
./commonapi-someip-generator-linux-x86_64 \\
    -data $WORK_DIR/someip_workspace \\
    -configuration $WORK_DIR/someip_config \\
    -dest {output_dir} {fdepl_path}

# Clean up JSON catalog files
find {output_dir} -name "*.json" -delete

# Verify all expected files were generated
EXPECTED_COUNT={file_count}
ACTUAL_COUNT=$(find {output_dir} -name "*.hpp" -o -name "*.cpp" | wc -l)
if [ "$ACTUAL_COUNT" -ne "$EXPECTED_COUNT" ]; then
    echo "ERROR: Expected $EXPECTED_COUNT files but found $ACTUAL_COUNT"
    exit 1
fi

echo "✓ Code generation completed: $ACTUAL_COUNT files"
""".format(
        output_dir = output_dir,
        core_gen_dir = core_gen_dir,
        someip_gen_dir = someip_gen_dir,
        fidl_path = fidl_file.path,
        fdepl_path = fdepl_file.path,
        file_count = len(_GENERATED_FILES),
    )
    
    ctx.actions.write(
        output = script,
        content = script_content,
        is_executable = True,
    )
    
    # Run the code generation action
    ctx.actions.run(
        inputs = depset(
            direct = [fidl_file, fdepl_file, script],
            transitive = [
                ctx.attr.core_generator.files,
                ctx.attr.someip_generator.files,
            ],
        ),
        outputs = output_files,
        executable = script,
        execution_requirements = {
            "no-sandbox": "1",  # Generators need writable workspace
        },
        mnemonic = "CommonAPICodegen",
        progress_message = "Generating CommonAPI code from %s" % fidl_file.short_path,
    )
    
    # Separate headers and sources
    hdrs = [f for f in output_files if f.path.endswith(".hpp")]
    srcs = [f for f in output_files if f.path.endswith(".cpp")]
    
    return [
        DefaultInfo(files = depset(output_files)),
        OutputGroupInfo(
            hdrs = depset(hdrs),
            srcs = depset(srcs),
        ),
    ]

commonapi_library = rule(
    implementation = _commonapi_library_impl,
    attrs = {
        "fidl": attr.label(
            allow_single_file = [".fidl"],
            mandatory = True,
            doc = "FIDL interface definition file",
        ),
        "fdepl": attr.label(
            allow_single_file = [".fdepl"],
            mandatory = True,
            doc = "SomeIP deployment specification file",
        ),
        "core_generator": attr.label(
            mandatory = True,
            doc = "CommonAPI core code generator",
        ),
        "someip_generator": attr.label(
            mandatory = True,
            doc = "CommonAPI SomeIP code generator",
        ),
    },
    doc = "Generates C++ code from FIDL and SomeIP deployment files using CommonAPI generators",
)

