# Middleware utilities library

load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "serialization",
    hdrs = ["serialization.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//middleware/data:data",
    ],
)
