# Middleware library aggregation

load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "middleware",
    visibility = ["//visibility:public"],
    deps = [
        "//middleware/data:data",
        "//middleware/utils:serialization",
    ],
)
