# Middleware data structures library

load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "data",
    hdrs = [
        "vehicle_state.h",
        "scene_state.h",
        "control_command.h",
        "sensor_data.h",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "vehicle_state",
    hdrs = ["vehicle_state.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "scene_state",
    hdrs = ["scene_state.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "control_command",
    hdrs = ["control_command.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "sensor_data",
    hdrs = ["sensor_data.h"],
    visibility = ["//visibility:public"],
)
